from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    hour, col, to_date, current_date, date_sub, 
    sum as spark_sum, desc
)
from pyspark.sql.window import Window
import os
from datetime import datetime, timedelta

# Initialize Spark
spark = SparkSession.builder \
    .appName("DailyTrafficBatch") \
    .config("spark.jars.packages", "org.postgresql:postgresql:42.6.0") \
    .getOrCreate()

spark.sparkContext.setLogLevel("WARN")

# Path to data (generated by the stream job)
data_path = "./data/traffic_history"

if not os.path.exists(data_path) or len(os.listdir(data_path)) == 0:
    print("No data found yet. Archive must run first.")
    spark.stop()
    exit()

print("="*60)
print("Starting Daily Batch Job - Peak Traffic Analysis")
print("="*60)

# 1. Load Data from Parquet
df = spark.read.parquet(data_path)

# 2. Filter for Yesterday's Data (or latest available date for testing)
# Convert timestamp to date
df = df.withColumn("date", to_date(col("timestamp")))

# Get distinct dates to check what data we have
available_dates = df.select("date").distinct().orderBy(desc("date")).limit(5)
print("\nAvailable dates in dataset:")
available_dates.show()

# Filter for yesterday's data (for production) or latest date (for testing)
yesterday = (datetime.now() - timedelta(days=1)).date()
print(f"\nProcessing data for: {yesterday}")

# For testing: if no yesterday data, use the latest available date
date_count = df.filter(col("date") == yesterday.isoformat()).count()
if date_count == 0:
    print(f"No data for {yesterday}, using latest available date...")
    latest_date = df.select("date").orderBy(desc("date")).first()[0]
    target_date = latest_date
    print(f"Processing date: {target_date}")
else:
    target_date = yesterday

df_filtered = df.filter(col("date") == str(target_date))

# 3. Extract Hour and Calculate Traffic per Junction per Hour
df_with_hour = df_filtered.withColumn("hour", hour(col("timestamp")))

# Group by Junction and Hour to get total vehicle count
hourly_traffic = df_with_hour.groupBy("sensor_id", "hour") \
    .agg(spark_sum("vehicle_count").alias("total_count")) \
    .orderBy("sensor_id", "hour")

print("\nHourly traffic summary:")
hourly_traffic.show(50)

# 4. Find Peak Traffic Hour per Junction (hour with maximum vehicles)
# Using window function to rank hours by traffic volume per junction
window_spec = Window.partitionBy("sensor_id").orderBy(desc("total_count"))

from pyspark.sql.functions import row_number, lit as spark_lit

peak_traffic = hourly_traffic \
    .withColumn("rank", row_number().over(window_spec)) \
    .filter(col("rank") == 1) \
    .select(
        col("sensor_id").alias("junction_id"),
        col("hour").alias("peak_hour"),
        col("total_count").alias("max_vehicle_count")
    ) \
    .withColumn("report_date", spark_lit(str(target_date)))

print("\n" + "="*60)
print("PEAK TRAFFIC HOURS PER JUNCTION")
print("="*60)
peak_traffic.show(truncate=False)

# 5. Identify junctions requiring intervention (highest congestion)
print("\n" + "="*60)
print("JUNCTIONS REQUIRING TRAFFIC POLICE INTERVENTION:")
print("(Sorted by traffic volume)")
print("="*60)
intervention_report = peak_traffic.orderBy(desc("max_vehicle_count"))
intervention_report.show(truncate=False)

# 6. Write Report to PostgreSQL
try:
    peak_traffic.write \
        .format("jdbc") \
        .option("url", "jdbc:postgresql://localhost:5432/smartcity_db") \
        .option("dbtable", "peak_traffic_stats") \
        .option("user", "admin") \
        .option("password", "password") \
        .option("driver", "org.postgresql.Driver") \
        .mode("append") \
        .save()
    
    print("\n✓ Batch Job Complete. Report saved to database.")
    print(f"  - Date processed: {target_date}")
    print(f"  - Records written: {peak_traffic.count()}")
    print("="*60)
except Exception as e:
    print(f"Error writing to database: {e}")
    print("Make sure PostgreSQL is running and accessible.")

spark.stop()